<?php

namespace ContainerCI9miGd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FBlrqgwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fBlrqgw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fBlrqgw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidat' => ['privates', '.errored..service_locator.fBlrqgw.App\\Entity\\Candidat', NULL, 'Cannot autowire service ".service_locator.fBlrqgw": it references class "App\\Entity\\Candidat" but no such service exists.'],
        ], [
            'candidat' => 'App\\Entity\\Candidat',
        ]);
    }
}
