<?php

namespace ContainerCI9miGd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HfELiSKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hfELiSK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hfELiSK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CandidatController::delete' => ['privates', '.service_locator.QNK8YYB', 'get_ServiceLocator_QNK8YYBService', true],
            'App\\Controller\\CandidatController::edit' => ['privates', '.service_locator.QNK8YYB', 'get_ServiceLocator_QNK8YYBService', true],
            'App\\Controller\\CandidatController::index' => ['privates', '.service_locator.y.HmU96', 'get_ServiceLocator_Y_HmU96Service', true],
            'App\\Controller\\CandidatController::new' => ['privates', '.service_locator.y.HmU96', 'get_ServiceLocator_Y_HmU96Service', true],
            'App\\Controller\\CandidatController::show' => ['privates', '.service_locator.fBlrqgw', 'get_ServiceLocator_FBlrqgwService', true],
            'App\\Controller\\OffreController::delete' => ['privates', '.service_locator.uQRUBkf', 'get_ServiceLocator_UQRUBkfService', true],
            'App\\Controller\\OffreController::edit' => ['privates', '.service_locator.uQRUBkf', 'get_ServiceLocator_UQRUBkfService', true],
            'App\\Controller\\OffreController::index' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController::indexFront' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController::new' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController::newFront' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController::show' => ['privates', '.service_locator.6rKICIw', 'get_ServiceLocator_6rKICIwService', true],
            'App\\Controller\\OffreController::showFront' => ['privates', '.service_locator.6rKICIw', 'get_ServiceLocator_6rKICIwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CandidatController:delete' => ['privates', '.service_locator.QNK8YYB', 'get_ServiceLocator_QNK8YYBService', true],
            'App\\Controller\\CandidatController:edit' => ['privates', '.service_locator.QNK8YYB', 'get_ServiceLocator_QNK8YYBService', true],
            'App\\Controller\\CandidatController:index' => ['privates', '.service_locator.y.HmU96', 'get_ServiceLocator_Y_HmU96Service', true],
            'App\\Controller\\CandidatController:new' => ['privates', '.service_locator.y.HmU96', 'get_ServiceLocator_Y_HmU96Service', true],
            'App\\Controller\\CandidatController:show' => ['privates', '.service_locator.fBlrqgw', 'get_ServiceLocator_FBlrqgwService', true],
            'App\\Controller\\OffreController:delete' => ['privates', '.service_locator.uQRUBkf', 'get_ServiceLocator_UQRUBkfService', true],
            'App\\Controller\\OffreController:edit' => ['privates', '.service_locator.uQRUBkf', 'get_ServiceLocator_UQRUBkfService', true],
            'App\\Controller\\OffreController:index' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController:indexFront' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController:new' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController:newFront' => ['privates', '.service_locator.ZDu8hFs', 'get_ServiceLocator_ZDu8hFsService', true],
            'App\\Controller\\OffreController:show' => ['privates', '.service_locator.6rKICIw', 'get_ServiceLocator_6rKICIwService', true],
            'App\\Controller\\OffreController:showFront' => ['privates', '.service_locator.6rKICIw', 'get_ServiceLocator_6rKICIwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CandidatController::delete' => '?',
            'App\\Controller\\CandidatController::edit' => '?',
            'App\\Controller\\CandidatController::index' => '?',
            'App\\Controller\\CandidatController::new' => '?',
            'App\\Controller\\CandidatController::show' => '?',
            'App\\Controller\\OffreController::delete' => '?',
            'App\\Controller\\OffreController::edit' => '?',
            'App\\Controller\\OffreController::index' => '?',
            'App\\Controller\\OffreController::indexFront' => '?',
            'App\\Controller\\OffreController::new' => '?',
            'App\\Controller\\OffreController::newFront' => '?',
            'App\\Controller\\OffreController::show' => '?',
            'App\\Controller\\OffreController::showFront' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CandidatController:delete' => '?',
            'App\\Controller\\CandidatController:edit' => '?',
            'App\\Controller\\CandidatController:index' => '?',
            'App\\Controller\\CandidatController:new' => '?',
            'App\\Controller\\CandidatController:show' => '?',
            'App\\Controller\\OffreController:delete' => '?',
            'App\\Controller\\OffreController:edit' => '?',
            'App\\Controller\\OffreController:index' => '?',
            'App\\Controller\\OffreController:indexFront' => '?',
            'App\\Controller\\OffreController:new' => '?',
            'App\\Controller\\OffreController:newFront' => '?',
            'App\\Controller\\OffreController:show' => '?',
            'App\\Controller\\OffreController:showFront' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
