<?php

namespace ContainerCI9miGd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QNK8YYB.App\Entity\Candidat' shared service.
     *
     * @return \App\Entity\Candidat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QNK8YYB": it references class "App\\Entity\\Candidat" but no such service exists.');
    }
}
