<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7WnKBP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7WnKBP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7WnKBP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7WnKBP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7WnKBP\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7WnKBP',
    'container.build_id' => '8dae90d0',
    'container.build_time' => 1678231293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7WnKBP');
