<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCI9miGd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCI9miGd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCI9miGd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCI9miGd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCI9miGd\App_KernelDevDebugContainer([
    'container.build_hash' => 'CI9miGd',
    'container.build_id' => '04a83f56',
    'container.build_time' => 1677100758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCI9miGd');
