<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_candidat_index' => [[], ['_controller' => 'App\\Controller\\CandidatController::index'], [], [['text', '/candidat/']], [], [], []],
    'app_candidat_new' => [[], ['_controller' => 'App\\Controller\\CandidatController::new'], [], [['text', '/candidat/new']], [], [], []],
    'app_candidat_show' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], [], []],
    'app_candidat_edit' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], [], []],
    'app_candidat_delete' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], [], []],
    'app_front' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/front']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\HomeController::dashboard'], [], [['text', '/dashboard']], [], [], []],
    'app_offre_index' => [[], ['_controller' => 'App\\Controller\\OffreController::index'], [], [['text', '/offre/']], [], [], []],
    'app_offre_index_front' => [[], ['_controller' => 'App\\Controller\\OffreController::indexFront'], [], [['text', '/offre/viewOffres']], [], [], []],
    'app_offre_new_front' => [[], ['_controller' => 'App\\Controller\\OffreController::newFront'], [], [['text', '/offre/newOffre']], [], [], []],
    'app_offre_new' => [[], ['_controller' => 'App\\Controller\\OffreController::new'], [], [['text', '/offre/new']], [], [], []],
    'app_offre_show' => [['id'], ['_controller' => 'App\\Controller\\OffreController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/offre']], [], [], []],
    'app_offre_show_front' => [['id'], ['_controller' => 'App\\Controller\\OffreController::showFront'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/offre/viewOffre']], [], [], []],
    'app_offre_edit' => [['id'], ['_controller' => 'App\\Controller\\OffreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/offre']], [], [], []],
    'app_offre_delete' => [['id'], ['_controller' => 'App\\Controller\\OffreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/offre']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
